apiVersion: v1
kind: Service
metadata:
  
  labels:
    app: mariadb
    chart: mariadb-7.3.1
    component: master
    heritage: Helm
    release: wordpress-kops
  name: wordpress-kops-mariadb
  namespace: default
  
  selfLink: /api/v1/namespaces/default/services/wordpress-kops-mariadb
  
spec:
  
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: mariadb
    component: master
    release: wordpress-kops
  sessionAffinity: None
  type: ClusterIP

