apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 100.101.78.66/32
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      mariadb'
  
  labels:
    app: mariadb
    chart: mariadb-7.3.1
    component: master
    
    release: wordpress-kops
    statefulset.kubernetes.io/pod-name: wordpress-kops-mariadb-0
  name: wordpress-kops-mariadb-0
  namespace: default
  
    
  selfLink: /api/v1/namespaces/default/pods/wordpress-kops-mariadb-0
  
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: mariadb
              release: wordpress-kops
          topologyKey: kubernetes.io/hostname
        weight: 1
  containers:
  - env:
    - name: MARIADB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mariadb-root-password
          name: wordpress-kops-mariadb
    - name: MARIADB_USER
      value: bn_wordpress
    - name: MARIADB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mariadb-password
          name: wordpress-kops-mariadb
    - name: MARIADB_DATABASE
      value: bitnami_wordpress
    image: docker.io/bitnami/mariadb:10.3.21-debian-9-r0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - |
          password_aux="${MARIADB_ROOT_PASSWORD:-}"
          if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
              password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
          fi
          mysqladmin status -uroot -p$password_aux
      failureThreshold: 3
      initialDelaySeconds: 120
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: mariadb
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - |
          password_aux="${MARIADB_ROOT_PASSWORD:-}"
          if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
              password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
          fi
          mysqladmin status -uroot -p$password_aux
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    
    volumeMounts:
    - mountPath: /bitnami/mariadb
      name: data
    
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: wordpress-kops-mariadb-0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    
    fsGroup: 0
    runAsUser: 0
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-wordpress-kops-mariadb-0
  

