apiVersion: v1
kind: Service
metadata:
  
  labels:
    app: wordpress-kops
    chart: wordpress-8.0.3
    heritage: Helm
    release: wordpress-kops
  name: wordpress-kops
  namespace: default
  
  selfLink: /api/v1/namespaces/default/services/wordpress-kops
  
spec:
  
  
  ports:
  - name: http
    nodePort: 31751
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30946
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: wordpress-kops
  sessionAffinity: None
  type: LoadBalancer

