apiVersion: v1
data:
  wordpress-password: ZGVTZHR4b082eA==
kind: Secret
metadata:
  
  labels:
    app: wordpress-kops
    chart: wordpress-8.0.3
    heritage: Helm
    release: wordpress-kops
  name: wordpress-kops
  namespace: default
  
  selfLink: /api/v1/namespaces/default/secrets/wordpress-kops
  
type: Opaque
